name: Asset publish

on:
  release:
    types:
      - published

jobs:
  publish-assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up JDK for x64
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          architecture: x64
          cache: gradle
          java-version-file: ./.java-version

      - name: Setup variables
        id: variables
        shell: bash
        run: |
          VERSION=$(cat gradle.properties | sed "s/version=//g")
          
          echo "Version: ${VERSION}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build asset
        run: ./gradlew build

      - name: Upload asset
        id: upload-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/libs/openpages-support-${{ steps.variables.outputs.version }},jar
          asset_name: openpages-support-${{ steps.variables.outputs.version }}.jar
          asset_content_type: application/octet-stream
