name: Docker build

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK for x64
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          architecture: x64
          cache: gradle

      - name: Test with Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build
