name: Release module

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK for x64
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          architecture: x64
          cache: gradle

      - name: Test with Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

  release:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release
        id: create-release
        uses: release-drafter/release-drafter@v6
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release-drafter.yaml
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup variables
        id: variables
        shell: bash
        run: |
          VERSION=$(echo "${{ steps.create-release.outputs.tag_name }}" | | sed "s/v//g")
          
          echo "Version: ${VERSION}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update gradle.properties
        run: echo "version=${{ steps.variables.outputs.version }}" > gradle.properties

      - name: Commit gradle.properties
        run: |
          git config --local user.email cloudnativetoolkit@gmail.com
          git config --local user.name "Cloud-Native Toolkit"
          git commit -a -m "Update version to ${{ steps.variables.outputs.version }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        id: publish-release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yaml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
